fmod LIST is
	sorts Elt List.
	subsort Elt < List.
	op nil : −> List[ctor].
	op : List List −> List [ctor assoc id: nil].
endfm

fmod LISTOFNATS is
	protecting NAT.
	protecting LIST.

	op cons (_ _) : Nat List −> List.
	op head (_) : List −> Nat.
	op tail (_) : List −> List.
	var N : Nat.
	var L : List.

	eq head ( cons ( N nil ) ) = N.
	eq head ( cons ( N L ) ) = N.
	eq tail ( cons ( N nil ) ) = nil.
	eq tail ( cons ( N L ) ) = L.
endfm
